# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-03-12 11:33
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Record',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('active', models.BooleanField(default=True)),
                ('name', models.CharField(db_index=True, max_length=256, unique=True)),
                ('description', models.TextField(null=True)),
            ],
        ),
        migrations.AlterIndexTogether(
            name='record',
            index_together=set([('active', 'name')]),
        ),
    ]
