# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-03-14 14:49
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dt', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='RecordPage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('page', models.IntegerField(db_index=True, default=0)),
                ('record', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dt.Record', unique=True)),
            ],
        ),
        migrations.AlterUniqueTogether(
            name='recordpage',
            unique_together=set([('record', 'page')]),
        ),
        migrations.AlterIndexTogether(
            name='recordpage',
            index_together=set([('record', 'page')]),
        ),
    ]
