export WINDSEED_DOMAIN="windseed.com"

export WINDSEED_SUPERUSER_EMAIL="superuser@windseed.com"
export WINDSEED_SUPERUSER_PASSWORD="superuser"

export WINDSEED_COOKIE_SECRET="__COOKIE_SECRET__"

export WINDSEED_DBNAME="windseed"
export WINDSEED_MAX_CONNECTIONS="32"
export WINDSEED_STALE_TIMEOUT="120"
export WINDSEED_USER="windseed"
export WINDSEED_PASSWORD="windseed"
export WINDSEED_HOST="localhost"
export WINDSEED_PORT="5432"

export WINDSEED_RECORD_COUNT="10000"

export WINDSEED_RELATED_ITEMS_PER_PAGE="100"
export WINDSEED_ADMIN_ITEMS_PER_PAGE="20"

export WINDSEED_RECORDS_PER_PAGE="48"
export WINDSEED_SITEMAP_PER_PAGE="100"
